name: Deploy CIPP-API (upstream) to Azure Functions

on:
  workflow_dispatch: {}
  push:
    branches: [ master ]  # keep if you want auto-deploys too

jobs:
  deploy:
    runs-on: windows-latest
    steps:
      - name: Checkout official upstream CIPP-API
        uses: actions/checkout@v4
        with:
          repository: KelvinTegelaar/CIPP-API
          ref: master
          fetch-depth: 1

      - name: Deploy to Azure Function App
        uses: Azure/functions-action@v1
        with:
          app-name: cippdh3p2        # <-- your Function App name
          package: '.'
          publish-profile: ${{ secrets.AZURE_FUNCTIONAPP_PUBLISH_PROFILE }}
